#!/bin/bash

# Extract ife's party comments to escenario n

# Fill by hand (to make executable, this would need to be automated)
edo="zac"
edon="32"
prefix="Zacatecas_2"
#
# unzip and rename target file
case="panloc"
unzip "$prefix"_32_"$edon".zip
mv escenario.dat.ife "$edo"2"$case".csv
rm distritos.dat.ife procesos.dat.ife
#
case="priloc"
unzip "$prefix"_33_"$edon".zip
mv escenario.dat.ife "$edo"2"$case".csv
rm distritos.dat.ife procesos.dat.ife
#
case="prdloc"
unzip "$prefix"_34_"$edon".zip
mv escenario.dat.ife "$edo"2"$case".csv
rm distritos.dat.ife procesos.dat.ife
#
case="pannac"
unzip "$prefix"_42_"$edon".zip
mv escenario.dat.ife "$edo"2"$case".csv
rm distritos.dat.ife procesos.dat.ife
#
case="prinac"
unzip "$prefix"_43_"$edon".zip
mv escenario.dat.ife "$edo"2"$case".csv
rm distritos.dat.ife procesos.dat.ife
#
case="prdnac"
unzip "$prefix"_44_"$edon".zip
mv escenario.dat.ife "$edo"2"$case".csv
rm distritos.dat.ife procesos.dat.ife

# move unzipped to working dir (done in 2nd step)
edo="1ags"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="2bc"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="3bcs"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="4cam"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="5coa"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="6col"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="7cps"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="8cua"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="9df"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="10dgo"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="11gua"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="12gue"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="13hgo"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="14jal"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="15mex"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="16mic"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="17mor"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="18nay"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="19nl"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="20oax"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="21pue"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="22que"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="23qui"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="24san"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="25sin"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="26son"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="27tab"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="28tam"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="29tla"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="30ver"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="31yuc"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/
edo="32zac"
cd /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/ifeRedist2013/2oEscenarioComentariosPartidos/"$edo"/Escenarios/
mv *.csv /home/eric/Desktop/data/elecs/MXelsCalendGovt/redistrict/git-repo/mex-open-map/data/ptyReactions2escenarios/

